### ISSUE TITLE
WKND Sites basic tutorial - Issue playing video

### ISSUE THREAD

**Issue by SebaMMM** [AdobeDocs/experience-manager-learn.en#95] opened 2022-10-19 13:17 UTC
Issue in ./help/getting-started-wknd-tutorial-develop/project-archetype/pages-templates.md

Hello, the video explaining how to Update the Header and Footer with Experience Fragments won't go past the 2nd minute & 47th second. I have tried with different browsers. Previous videos didn't have problems. Thank you for your time!

![image](https://user-images.githubusercontent.com/93770591/196701147-24a118fd-9bf7-4888-98a1-3f079108cdc6.png)

**Comment by davidjgonzalez** [comment] 2022-10-19 17:34
Hi @SebaMMM  - unfortunately i cannot reproduce this. Here's a screenshot of my video played well past 2:47 -- can you a different browser, incognito, etc? Or maybe  try adjusting the quality and see if that helps?

![2022-10-19 at 1 33 PM](https://user-images.githubusercontent.com/1451868/196763920-37da022c-1794-44d0-978f-3961e416e4c4.png)

**Comment by davidjgonzalez** [comment] 2022-10-20 12:59
Closing for now. Please re-open if you still cannot play the video and we can raise w/ our engineering team.

**Closed as completed by davidjgonzalez** 2022-10-20 12:59 UTC
Labels: AEM Sites, Cannot reproduce
